// ============================================================
//  news-data.js — GRC Prep Studio
//  Aggiornato automaticamente il 2026-07-10 10:26 UTC
//  Script: update_news.py | GitHub Actions
// ============================================================

const NEWS = [
  {
    "id": "news-4fd31aee",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "Attackers Exploit 'Ill Bloom' Vulnerability to Drain $3.1 Million From Cryptocurrency Wallets",
    "titleIT": "Attackers Exploit 'Ill Bloom' Vulnerability to Drain $3.1 Million From Cryptocurrency Wallets",
    "excerptEN": "Security firm Coinspect has disclosed a crypto wallet flaw it calls Ill Bloom, and attackers are already using it. The flaw is in how some wallet software generated its recovery phrase, the words...",
    "excerptIT": "[Sicurezza] Security firm Coinspect has disclosed a crypto wallet flaw it calls Ill Bloom, and attackers are already using it. The flaw is in how some wallet software generated its recovery...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/attackers-exploit-ill-bloom.html"
  },
  {
    "id": "news-1f23b306",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "Ransomware Negotiator Gets 70 Months in Prison for Aiding BlackCat Attacks",
    "titleIT": "Ransomware Negotiator Gets 70 Months in Prison for Aiding BlackCat Attacks",
    "excerptEN": "A 41-year-old former ransomware negotiator has been sentenced to nearly six years (i.e., 70 months) in prison in the U.S. for their role in conspiring with the now-defunct BlackCat ransomware...",
    "excerptIT": "[Sicurezza] A 41-year-old former ransomware negotiator has been sentenced to nearly six years (i.e., 70 months) in prison in the U.S. for their role in conspiring with the now-defunct...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/ransomware-negotiator-gets-70-months-in.html"
  },
  {
    "id": "news-7b3eba50",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "Anonimizzazione, le nuove linee guida EDPB: dalla tecnica al processo di assessment",
    "titleIT": "Anonimizzazione, le nuove linee guida EDPB: dalla tecnica al processo di assessment",
    "excerptEN": "Le nuove Guidelines 02/2026 dell’EDPB trasformano l’anonimizzazione da tecnica a processo di assessment continuo. Tra rischio di re-identificazione, AI e accountability, l’obiettivo non è solo uscire...",
    "excerptIT": "[Sicurezza] Le nuove Guidelines 02/2026 dell’EDPB trasformano l’anonimizzazione da tecnica a processo di assessment continuo. Tra rischio di re-identificazione, AI e accountability,...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/legal/privacy-dati-personali/anonimizzazione-le-nuove-linee-guida-edpb-dalla-tecnica-al-processo-di-assessment/"
  },
  {
    "id": "news-2cd22635",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "L’AI ridefinisce la sovranità dei dati: le nuove priorità per i leader IT",
    "titleIT": "L’AI ridefinisce la sovranità dei dati: le nuove priorità per i leader IT",
    "excerptEN": "Con l’accelerazione dell’adozione dell’AI enterprise, le organizzazioni sono sottoposte a una crescente pressione per mantenere visibilità, governance e controllo sui dati sensibili in ambienti...",
    "excerptIT": "[Sicurezza] Con l’accelerazione dell’adozione dell’AI enterprise, le organizzazioni sono sottoposte a una crescente pressione per mantenere visibilità, governance e controllo sui dati...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/legal/lai-ridefinisce-la-sovranita-dei-dati-le-nuove-priorita-per-i-leader-it/"
  },
  {
    "id": "news-f2fbdc74",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "Governance by design: come costruire organizzazioni che pensano prima di agire",
    "titleIT": "Governance by design: come costruire organizzazioni che pensano prima di agire",
    "excerptEN": "Bisogna smettere di progettare faldoni di documenti e, finalmente, iniziare a progettare le decisioni. Ecco i pilastri della governance by design come modello integrato di direzione aziendale...",
    "excerptIT": "[Sicurezza] Bisogna smettere di progettare faldoni di documenti e, finalmente, iniziare a progettare le decisioni. Ecco i pilastri della governance by design come modello integrato di...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/legal/governance-by-design-come-costruire-organizzazioni-che-pensano-prima-di-agire/"
  },
  {
    "id": "news-17e4e7c5",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Tech",
    "titleEN": "Cavi sottomarini, la Fcc vara nuove regole per accelerare la posa",
    "titleIT": "Cavi sottomarini, la Fcc vara nuove regole per accelerare la posa",
    "excerptEN": "L'obiettivo principale del framework è quello di snellire la burocrazia per gli operatori considerati affidabili, così da tenere il passo con le esigenze di calcolo e connettività generate dalla...",
    "excerptIT": "[Tecnologia] L'obiettivo principale del framework è quello di snellire la burocrazia per gli operatori considerati affidabili, così da tenere il passo con le esigenze di calcolo e connettività...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/telco/banda-ultralarga/cavi-sottomarini-la-fcc-vara-nuove-regole-per-accelerare-la-posa/"
  },
  {
    "id": "news-e78c17a4",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Tech",
    "titleEN": "AI trust gap: nelle telco il 72% si fida, ma solo il 14% può provarlo",
    "titleIT": "AI trust gap: nelle telco il 72% si fida, ma solo il 14% può provarlo",
    "excerptEN": "La nuova ricerca TM Forum, realizzata con Ibm Institute for Business Value su 130 operatori, evidenzia un divario critico tra governance e assurance. Per il settore la questione non è più solo...",
    "excerptIT": "[Tecnologia] La nuova ricerca TM Forum, realizzata con Ibm Institute for Business Value su 130 operatori, evidenzia un divario critico tra governance e assurance. Per il settore la questione...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/telco/ai-trust-gap-nelle-telco-il-72-si-fida-ma-solo-il-14-puo-provarlo/"
  },
  {
    "id": "news-66a1cdfc",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Tech",
    "titleEN": "Semiconduttori, per l’Europa il rischio geopolitico diventa strutturale",
    "titleIT": "Semiconduttori, per l’Europa il rischio geopolitico diventa strutturale",
    "excerptEN": "Il policy paper della Chips Diplomacy Support Initiative avverte: nei prossimi cinque anni restrizioni all’export, tensioni su Taiwan e fragilità delle filiere metteranno alla prova la capacità di...",
    "excerptIT": "[Tecnologia] Il policy paper della Chips Diplomacy Support Initiative avverte: nei prossimi cinque anni restrizioni all’export, tensioni su Taiwan e fragilità delle filiere metteranno alla...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/europa/semiconduttori-per-leuropa-il-rischio-geopolitico-diventa-strutturale/"
  },
  {
    "id": "news-40cf687d",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Tech",
    "titleEN": "Sovranità digitale, l’Europa rischia una doppia dipendenza su energia e AI",
    "titleIT": "Sovranità digitale, l’Europa rischia una doppia dipendenza su energia e AI",
    "excerptEN": "La capacità di controllare infrastrutture critiche, modelli AI, reti elettriche e filiere pulite diventa il nuovo baricentro competitivo. Il brief Iai-Cep indica una strategia integrata per evitare...",
    "excerptIT": "[Tecnologia] La capacità di controllare infrastrutture critiche, modelli AI, reti elettriche e filiere pulite diventa il nuovo baricentro competitivo. Il brief Iai-Cep indica una strategia...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/europa/sovranita-digitale-leuropa-rischia-una-doppia-dipendenza-su-energia-e-ai/"
  },
  {
    "id": "news-e8de51e8",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "New GigaWiper Windows Backdoor Bundles Disk Wiping, Fake Ransomware, and Spyware",
    "titleIT": "New GigaWiper Windows Backdoor Bundles Disk Wiping, Fake Ransomware, and Spyware",
    "excerptEN": "Microsoft has taken apart a destructive Windows backdoor it calls GigaWiper. What stands out is how it is built: not one tool but three older destructive programs bolted into one, offered as commands...",
    "excerptIT": "[Sicurezza] Microsoft has taken apart a destructive Windows backdoor it calls GigaWiper. What stands out is how it is built: not one tool but three older destructive programs bolted into one,...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/new-gigawiper-windows-backdoor-bundles.html"
  },
  {
    "id": "news-5ca923f6",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "npm 12 Disables Install Scripts by Default to Reduce Supply Chain Risk",
    "titleIT": "npm 12 Disables Install Scripts by Default to Reduce Supply Chain Risk",
    "excerptEN": "GitHub has officially announced the release of npm version 12 with install scripts disabled by default, along with deprecating granular access tokens (GATs) designed to bypass two-factor...",
    "excerptIT": "[Sicurezza] GitHub has officially announced the release of npm version 12 with install scripts disabled by default, along with deprecating granular access tokens (GATs) designed to bypass...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/npm-12-disables-install-scripts-by.html"
  },
  {
    "id": "news-b8ebd8a6",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "ThreatsDay: Cloud Bucket Hijacking, Windows LPE Chain, Global Fraud Bust + 17 More Stories",
    "titleIT": "ThreatsDay: Cloud Bucket Hijacking, Windows LPE Chain, Global Fraud Bust + 17 More Stories",
    "excerptEN": "Most security mess starts as admin work. A link gets clicked. A tool gets trusted. A bucket name gets reused. A setting stays loose because nobody wants to touch it. This week is full of that kind of...",
    "excerptIT": "[Sicurezza] Most security mess starts as admin work. A link gets clicked. A tool gets trusted. A bucket name gets reused. A setting stays loose because nobody wants to touch it. This week is...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/threatsday-cloud-bucket-hijacking.html"
  },
  {
    "id": "news-9f61baaf",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "Iran's Cyber Crosshairs Focus Beyond Critical Infrastructure",
    "titleIT": "Iran's Cyber Crosshairs Focus Beyond Critical Infrastructure",
    "excerptEN": "Obscurity isn't a defense. If your company has any Internet-facing vulnerability, you're at risk from multiple threats.",
    "excerptIT": "[Sicurezza] Obscurity isn't a defense. If your company has any Internet-facing vulnerability, you're at risk from multiple threats.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyber-risk/iran-cyber-crosshairs-beyond-critical-infrastructure"
  },
  {
    "id": "news-846ad9f2",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "Microsoft Reins in RoguePlanet Zero-Day Threat",
    "titleIT": "Microsoft Reins in RoguePlanet Zero-Day Threat",
    "excerptEN": "The researcher known as \"Nightmare-Eclipse\" published a proof-of-concept (PoC) exploit for the Windows Defender vulnerability in early June after dropping several other Microsoft zero-days.",
    "excerptIT": "[Sicurezza] The researcher known as \"Nightmare-Eclipse\" published a proof-of-concept (PoC) exploit for the Windows Defender vulnerability in early June after dropping several other Microsoft...",
    "icon": "🔐",
    "link": "https://www.darkreading.com/vulnerabilities-threats/microsoft-rogueplanet-zero-day-threat"
  },
  {
    "id": "news-2c741960",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "AI Gateways Offer Attackers the Keys to the Kingdom",
    "titleIT": "AI Gateways Offer Attackers the Keys to the Kingdom",
    "excerptEN": "A cryptomining incident highlights how AI gateways can provide access to AI models, cloud infrastructure, and identity and access management (IAM) data.",
    "excerptIT": "[Sicurezza] A cryptomining incident highlights how AI gateways can provide access to AI models, cloud infrastructure, and identity and access management (IAM) data.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyber-risk/ai-gateways-keys-kingdom"
  },
  {
    "id": "news-346a0cf7",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "'GodDamn' Ransomware Uses BYOVD to Smite US Companies",
    "titleIT": "'GodDamn' Ransomware Uses BYOVD to Smite US Companies",
    "excerptEN": "Microsoft signed a malicious kernel driver, and now it's being used to kill security software in ransomware attacks.",
    "excerptIT": "[Sicurezza] Microsoft signed a malicious kernel driver, and now it's being used to kill security software in ransomware attacks.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyberattacks-data-breaches/goddamn-ransomware-byovd-smite-companies"
  },
  {
    "id": "news-4f1c3e05",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "The Language of AI Could Change How Humans Speak",
    "titleIT": "The Language of AI Could Change How Humans Speak",
    "excerptEN": "Because of the way they are trained, large language models capture only a slice of human language. They’re trained on the written word, from textbooks to social media posts, and our speech as...",
    "excerptIT": "[Sicurezza] Because of the way they are trained, large language models capture only a slice of human language. They’re trained on the written word, from textbooks to social media posts, and...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/the-language-of-ai-could-change-how-humans-speak.html"
  },
  {
    "id": "news-bc437fab",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "Indirect prompt injection: il phishing che non deve ingannare nessuno, tranne l’AI",
    "titleIT": "Indirect prompt injection: il phishing che non deve ingannare nessuno, tranne l’AI",
    "excerptEN": "Le nuove campagne di phishing puntano non a ingannare una persona, bensì l’intelligenza artificiale. Soprattutto l'agente AI che naviga il web in autonomia, confronta fonti e, in alcuni casi, esegue...",
    "excerptIT": "[Sicurezza] Le nuove campagne di phishing puntano non a ingannare una persona, bensì l’intelligenza artificiale. Soprattutto l'agente AI che naviga il web in autonomia, confronta fonti e, in...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/nuove-minacce/indirect-prompt-injection-il-phishing-che-non-deve-ingannare-nessuno-tranne-lai/"
  },
  {
    "id": "news-d90c226b",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "Compliance e tutela del patrimonio informativo: le linee guida per la gestione del rischio legale",
    "titleIT": "Compliance e tutela del patrimonio informativo: le linee guida per la gestione del rischio legale",
    "excerptEN": "La protezione dati è una leva strategica di mitigazione del rischio legale: sanzioni fino al 4% del fatturato globale, responsabilità penale personale e danni reputazionali rendono la compliance non...",
    "excerptIT": "[Sicurezza] La protezione dati è una leva strategica di mitigazione del rischio legale: sanzioni fino al 4% del fatturato globale, responsabilità penale personale e danni reputazionali...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/legal/privacy-dati-personali/compliance-e-tutela-del-patrimonio-informativo-le-linee-guida-per-la-gestione-del-rischio-legale/"
  },
  {
    "id": "news-76a9a6a4",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Tech",
    "titleEN": "Buono Digitale: le imprese chiedono una misura triennale in Legge di Bilancio",
    "titleIT": "Buono Digitale: le imprese chiedono una misura triennale in Legge di Bilancio",
    "excerptEN": "Il Manifesto per l’Italia connessa punta su software, cloud, AI e cybersecurity per colmare il divario delle realtà più piccole, con benefici legati all’adozione effettiva L'articolo Buono Digitale:...",
    "excerptIT": "[Tecnologia] Il Manifesto per l’Italia connessa punta su software, cloud, AI e cybersecurity per colmare il divario delle realtà più piccole, con benefici legati all’adozione effettiva...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/digital-economy/buono-digitale-le-imprese-chiedono-una-misura-triennale-in-legge-di-bilancio/"
  },
  {
    "id": "news-bc2801a6",
    "date": "2026-07-08",
    "dateLabel": "Jul 08, 2026",
    "category": "Security",
    "titleEN": "Mexico's New Cyber Plan Faces Its First Real Test",
    "titleIT": "Mexico's New Cyber Plan Faces Its First Real Test",
    "excerptEN": "The Latin American nation's cybersecurity plan — still in the expansion phase — has to survive its own knockout round during the FIFA World Cup.",
    "excerptIT": "[Sicurezza] The Latin American nation's cybersecurity plan — still in the expansion phase — has to survive its own knockout round during the FIFA World Cup.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyber-risk/mexicos-cyber-plan-first-real-test"
  },
  {
    "id": "news-26ceb73b",
    "date": "2026-07-08",
    "dateLabel": "Jul 08, 2026",
    "category": "Security",
    "titleEN": "Felons, Fraudsters Flog Offensive Cybersecurity Startup",
    "titleIT": "Felons, Fraudsters Flog Offensive Cybersecurity Startup",
    "excerptEN": "A cybersecurity startup dangling millions of dollars to acquire zero-day security vulnerabilities in popular software is run by a pair of far-right conspiracy theorists and convicted felons whose...",
    "excerptIT": "[Sicurezza] A cybersecurity startup dangling millions of dollars to acquire zero-day security vulnerabilities in popular software is run by a pair of far-right conspiracy theorists and...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/felons-fraudsters-flog-offensive-cybersecurity-startup/"
  },
  {
    "id": "news-cf60e6da",
    "date": "2026-07-08",
    "dateLabel": "Jul 08, 2026",
    "category": "Security",
    "titleEN": "Cybersecurity and the Gap Between Skill and Ability",
    "titleIT": "Cybersecurity and the Gap Between Skill and Ability",
    "excerptEN": "Last week, national security agencies from the Five Eyes—that’s the rich, English-language-speaking countries club—jointly released a statement warning of the increasing cyber risks of AI models: in...",
    "excerptIT": "[Sicurezza] Last week, national security agencies from the Five Eyes—that’s the rich, English-language-speaking countries club—jointly released a statement warning of the increasing cyber...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/cybersecurity-and-the-gap-between-skill-and-ability.html"
  },
  {
    "id": "news-28a99d87",
    "date": "2026-07-06",
    "dateLabel": "Jul 06, 2026",
    "category": "ISACA",
    "titleEN": "Making AI-Powered Audits Understandable: A Practical Guide Using COBIT EDM05",
    "titleIT": "Making AI-Powered Audits Understandable: A Practical Guide Using COBIT EDM05",
    "excerptEN": "While AI is rapidly transforming internal audits, promising faster insights and broader coverages than traditional audit approaches, many stakeholders don't fully understand how AI works or why they...",
    "excerptIT": "[ISACA] While AI is rapidly transforming internal audits, promising faster insights and broader coverages than traditional audit approaches, many stakeholders don't fully understand how...",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/making-ai-powered-audits-understandable-a-practical-guide-using-cobit-edm05"
  },
  {
    "id": "news-dab761d2",
    "date": "2026-07-06",
    "dateLabel": "Jul 06, 2026",
    "category": "Security",
    "titleEN": "France to Stop Certifying Non-Quantum-Safe Encryption",
    "titleIT": "France to Stop Certifying Non-Quantum-Safe Encryption",
    "excerptEN": "France is accelerating its transition to post-quantum encryption: France’s cybersecurity agency ANSSI said on Tuesday it would stop certifying security products that lack quantum-resistant...",
    "excerptIT": "[Sicurezza] France is accelerating its transition to post-quantum encryption: France’s cybersecurity agency ANSSI said on Tuesday it would stop certifying security products that lack...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/france-to-stop-certifying-non-quantum-safe-encryption.html"
  },
  {
    "id": "news-8395757d",
    "date": "2026-07-02",
    "dateLabel": "Jul 02, 2026",
    "category": "ISACA",
    "titleEN": "Vulnerability Is Not a Bug: It’s a State of Being",
    "titleIT": "Vulnerability Is Not a Bug: It’s a State of Being",
    "excerptEN": "The moment we treat vulnerability as a checklist item to close instead of a condition to continuously manage, we are asking for trouble.",
    "excerptIT": "[ISACA] The moment we treat vulnerability as a checklist item to close instead of a condition to continuously manage, we are asking for trouble.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/vulnerability-is-not-a-bug-its-a-state-of-being"
  },
  {
    "id": "news-f3f6d1e9",
    "date": "2026-07-02",
    "dateLabel": "Jul 02, 2026",
    "category": "Security",
    "titleEN": "FBI Seizes NetNut Proxy Platform, Popa Botnet",
    "titleIT": "FBI Seizes NetNut Proxy Platform, Popa Botnet",
    "excerptEN": "The Federal Bureau of Investigation (FBI) said today it worked with industry partners to seize hundreds of domains associated with NetNut, a sprawling residential proxy service operated by the...",
    "excerptIT": "[Sicurezza] The Federal Bureau of Investigation (FBI) said today it worked with industry partners to seize hundreds of domains associated with NetNut, a sprawling residential proxy service...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/fbi-seizes-netnut-proxy-platform-popa-botnet/"
  },
  {
    "id": "news-204e3baf",
    "date": "2026-07-02",
    "dateLabel": "Jul 02, 2026",
    "category": "Security",
    "titleEN": "Cybersecurity Mission Creep in the US",
    "titleIT": "Cybersecurity Mission Creep in the US",
    "excerptEN": "Interesting paper: “ Cybersecurity Mission Creep .” Abstract: Cybersecurity is experiencing mission creep. Policymakers are casting more and more problems as issues of cybersecurity. So reframed,...",
    "excerptIT": "[Sicurezza] Interesting paper: “ Cybersecurity Mission Creep .” Abstract: Cybersecurity is experiencing mission creep. Policymakers are casting more and more problems as issues of...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/cybersecurity-mission-creep-in-the-us.html"
  },
  {
    "id": "news-bbe8bc36",
    "date": "2026-07-01",
    "dateLabel": "Jul 01, 2026",
    "category": "ISACA",
    "titleEN": "The CISO vs. Shadow AI Cold War",
    "titleIT": "The CISO vs. Shadow AI Cold War",
    "excerptEN": "Organizations' biggest artificial intelligence risk may not be the model, but how shadow AI is being adopted across the enterprise.",
    "excerptIT": "[ISACA] Organizations' biggest artificial intelligence risk may not be the model, but how shadow AI is being adopted across the enterprise.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/the-ciso-vs-shadow-ai-cold-war"
  },
  {
    "id": "news-876688e3",
    "date": "2026-06-30",
    "dateLabel": "Jun 30, 2026",
    "category": "ISACA",
    "titleEN": "The Grey-Zone Threat to AI Sovereignty, Subsea Sabotage, Connectivity and National Security",
    "titleIT": "The Grey-Zone Threat to AI Sovereignty, Subsea Sabotage, Connectivity and National Security",
    "excerptEN": "In an era of intensifying geopolitical competition, the sea is an often overlooked domain where matters of economic security, national resilience, technological advantage and state power overlap.",
    "excerptIT": "[ISACA] In an era of intensifying geopolitical competition, the sea is an often overlooked domain where matters of economic security, national resilience, technological advantage and...",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/the-grey-zone-threat-to-ai-sovereignty-subsea-sabotage-connectivity-and-national-security"
  }
];
