// ============================================================
//  news-data.js — GRC Prep Studio
//  Aggiornato automaticamente il 2026-09-11 12:07 UTC
//  Script: update_news.py | GitHub Actions
// ============================================================

const NEWS = [
  {
    "id": "news-9ba9435a",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Security",
    "titleEN": "Attackers Chain JFrog Artifactory Flaws to Gain Admin Control and Plant Backdoors",
    "titleIT": "Attackers Chain JFrog Artifactory Flaws to Gain Admin Control and Plant Backdoors",
    "excerptEN": "Attackers have chained two flaws in JFrog Artifactory, the repository that software build pipelines pull from, to take administrator control of self-hosted servers and plant backdoors, cloud security...",
    "excerptIT": "[Sicurezza] Attackers have chained two flaws in JFrog Artifactory, the repository that software build pipelines pull from, to take administrator control of self-hosted servers and plant...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/09/attackers-chain-jfrog-artifactory-flaws.html"
  },
  {
    "id": "news-3f36cb9e",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Security",
    "titleEN": "Cisco FMC Flaws Exploited to Steal Credentials and Deploy Qilin Ransomware",
    "titleIT": "Cisco FMC Flaws Exploited to Steal Credentials and Deploy Qilin Ransomware",
    "excerptEN": "Cisco has revealed that three distinct threat clusters linked to ransomware and state-sponsored attacks have been exploiting two recently patched Secure Firewall Management Center (FMC)...",
    "excerptIT": "[Sicurezza] Cisco has revealed that three distinct threat clusters linked to ransomware and state-sponsored attacks have been exploiting two recently patched Secure Firewall Management Center...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/09/cisco-fmc-flaws-exploited-to-steal.html"
  },
  {
    "id": "news-311d064a",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Security",
    "titleEN": "Indonesia Hit by Android Banking App-Cloning Campaign",
    "titleIT": "Indonesia Hit by Android Banking App-Cloning Campaign",
    "excerptEN": "The GoldFactory threat group exploits the Android Work Profile feature to deliver the Gigabud Trojan, while Mantax Otax spreads separately.",
    "excerptIT": "[Sicurezza] The GoldFactory threat group exploits the Android Work Profile feature to deliver the Gigabud Trojan, while Mantax Otax spreads separately.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/mobile-security/indonesia-android-banking-app-cloning-campaign"
  },
  {
    "id": "news-2673784f",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Security",
    "titleEN": "Aggiornamenti Android settembre 2026, corrette 180 vulnerabilità: cosa fare subito",
    "titleIT": "Aggiornamenti Android settembre 2026, corrette 180 vulnerabilità: cosa fare subito",
    "excerptEN": "Google ha rilasciato il bollettino di sicurezza Android per il mese di settembre 2026 con patch per 180 vulnerabilità, tra cui otto Remote Code Execution critiche nel componente System e quattro...",
    "excerptIT": "[Sicurezza] Google ha rilasciato il bollettino di sicurezza Android per il mese di settembre 2026 con patch per 180 vulnerabilità, tra cui otto Remote Code Execution critiche nel componente...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/news/aggiornamenti-android-settembre-2026-corrette-180-vulnerabilita-cosa-fare-subito/"
  },
  {
    "id": "news-b8d7f497",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Tech",
    "titleEN": "Cybersecurity Act 2, allarme reti: “il rip and replace” può frenare 5G e 6G",
    "titleIT": "Cybersecurity Act 2, allarme reti: “il rip and replace” può frenare 5G e 6G",
    "excerptEN": "Uno studio di Assembly Research avverte che la sostituzione uniforme degli apparati dei fornitori ad alto rischio entro 36 mesi potrebbe aumentare i costi, ridurre la concorrenza e incidere sulla...",
    "excerptIT": "[Tecnologia] Uno studio di Assembly Research avverte che la sostituzione uniforme degli apparati dei fornitori ad alto rischio entro 36 mesi potrebbe aumentare i costi, ridurre la concorrenza...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/cyber-security/cybersecurity-act-2-allarme-reti-il-rip-and-replace-puo-frenare-5g-e-6g/"
  },
  {
    "id": "news-abf18290",
    "date": "2026-09-11",
    "dateLabel": "Sep 11, 2026",
    "category": "Tech",
    "titleEN": "Data center, il retrofit accelera la corsa all’AI: più efficienza e meno costi",
    "titleIT": "Data center, il retrofit accelera la corsa all’AI: più efficienza e meno costi",
    "excerptEN": "Con la potenza elettrica sempre più difficile da ottenere e le applicazioni di intelligenza artificiale che rivoluzionano l'architettura dei data center, il rinnovamento delle infrastrutture...",
    "excerptIT": "[Tecnologia] Con la potenza elettrica sempre più difficile da ottenere e le applicazioni di intelligenza artificiale che rivoluzionano l'architettura dei data center, il rinnovamento delle...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/digital-economy/data-center-il-retrofit-accelera-la-corsa-allai-piu-efficienza-e-meno-costi/"
  },
  {
    "id": "news-e8059c60",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Security",
    "titleEN": "ThreatsDay: 200 Android Flaws, Browser-Built Phishing, 119K Scam Shops + 23 More Stories",
    "titleIT": "ThreatsDay: 200 Android Flaws, Browser-Built Phishing, 119K Scam Shops + 23 More Stories",
    "excerptEN": "A lot of this week’s security news has the same awkward answer to one question: “Why was that allowed to work?” An extension asks for access and takes too much. A trusted service becomes part of a...",
    "excerptIT": "[Sicurezza] A lot of this week’s security news has the same awkward answer to one question: “Why was that allowed to work?” An extension asks for access and takes too much. A trusted service...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/09/threatsday-200-android-flaws-browser.html"
  },
  {
    "id": "news-c2cc8ec0",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Security",
    "titleEN": "CISA Flags Exploited Cisco, Citrix, Fortinet Flaws, Sets Sept. 12 Federal Patch Deadline",
    "titleIT": "CISA Flags Exploited Cisco, Citrix, Fortinet Flaws, Sets Sept. 12 Federal Patch Deadline",
    "excerptEN": "The U.S. Cybersecurity and Infrastructure Security Agency (CISA) on Wednesday added three flaws, each impacting Cisco, Citrix, and Fortinet, to its Known Exploited Vulnerabilities (KEV) catalog,...",
    "excerptIT": "[Sicurezza] The U.S. Cybersecurity and Infrastructure Security Agency (CISA) on Wednesday added three flaws, each impacting Cisco, Citrix, and Fortinet, to its Known Exploited Vulnerabilities...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/09/cisa-flags-exploited-cisco-citrix.html"
  },
  {
    "id": "news-9b1b48c5",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Security",
    "titleEN": "Nearly 1 in 10 Exposed LiteLLM Gateways Accepted the Example \"sk-1234\" Admin Key",
    "titleIT": "Nearly 1 in 10 Exposed LiteLLM Gateways Accepted the Example \"sk-1234\" Admin Key",
    "excerptEN": "Nearly one in ten of the internet-facing LiteLLM servers that Wiz Research scanned in February accepted sk-1234, the example admin key in LiteLLM's own setup guide. LiteLLM is an open-source AI...",
    "excerptIT": "[Sicurezza] Nearly one in ten of the internet-facing LiteLLM servers that Wiz Research scanned in February accepted sk-1234, the example admin key in LiteLLM's own setup guide. LiteLLM is an...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/09/nearly-1-in-10-exposed-litellm-gateways.html"
  },
  {
    "id": "news-5bd80052",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Security",
    "titleEN": "Voice Callers Exploit BYOD to Reach Microsoft 365, Corporate Data",
    "titleIT": "Voice Callers Exploit BYOD to Reach Microsoft 365, Corporate Data",
    "excerptEN": "Threat actors are leveraging Microsoft's Graph API to identify lucrative targets, then passing their access to extortion groups like ShinyHunters.",
    "excerptIT": "[Sicurezza] Threat actors are leveraging Microsoft's Graph API to identify lucrative targets, then passing their access to extortion groups like ShinyHunters.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/threat-intelligence/voice-callers-exploit-byod-microsoft-365-corporate-data"
  },
  {
    "id": "news-8c20186e",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Security",
    "titleEN": "EU Cyber Resilience Act to Enforce New Reporting Requirements",
    "titleIT": "EU Cyber Resilience Act to Enforce New Reporting Requirements",
    "excerptEN": "Starting Friday, European organizations will have just 24 hours to notify the EU government any time they discover serious product security incidents.",
    "excerptIT": "[Sicurezza] Starting Friday, European organizations will have just 24 hours to notify the EU government any time they discover serious product security incidents.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cybersecurity-operations/eu-cyber-resilience-act-reporting-requirements"
  },
  {
    "id": "news-04927999",
    "date": "2026-09-10",
    "dateLabel": "Sep 10, 2026",
    "category": "Tech",
    "titleEN": "Alleanza Cloudera-Mistral, l’AI enterprise diventa sovrana",
    "titleIT": "Alleanza Cloudera-Mistral, l’AI enterprise diventa sovrana",
    "excerptEN": "L’intesa integra piattaforma ibrida e tecnologie di frontiera per consentire inferenza privata, personalizzazione e deployment su cloud, on-premise, edge e ambienti air-gapped, con più controllo su...",
    "excerptIT": "[Tecnologia] L’intesa integra piattaforma ibrida e tecnologie di frontiera per consentire inferenza privata, personalizzazione e deployment su cloud, on-premise, edge e ambienti air-gapped,...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/digital-economy/alleanza-cloudermistral-lai-enterprise-diventa-sovrana/"
  },
  {
    "id": "news-8268c393",
    "date": "2026-09-09",
    "dateLabel": "Sep 09, 2026",
    "category": "ISACA",
    "titleEN": "CommunITy Day Inspiration Stories: Plan Your Impact",
    "titleIT": "CommunITy Day Inspiration Stories: Plan Your Impact",
    "excerptEN": "ISACA chapters and members find a rich variety of meaningful ways to make a difference in their communities during ISACA's annual CommunITy Day of global volunteering.",
    "excerptIT": "[ISACA] ISACA chapters and members find a rich variety of meaningful ways to make a difference in their communities during ISACA's annual CommunITy Day of global volunteering.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/community-day-inspiration-stories-plan-your-impact"
  },
  {
    "id": "news-5994bd25",
    "date": "2026-09-09",
    "dateLabel": "Sep 09, 2026",
    "category": "Security",
    "titleEN": "Mythos Vulnerability Firehose Hits a Human Bottleneck",
    "titleIT": "Mythos Vulnerability Firehose Hits a Human Bottleneck",
    "excerptEN": "An analysis of Project Glasswing findings shows only a fraction of the bugs it has discovered have reached disclosure, and an even smaller number have been fixed.",
    "excerptIT": "[Sicurezza] An analysis of Project Glasswing findings shows only a fraction of the bugs it has discovered have reached disclosure, and an even smaller number have been fixed.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/application-security/mythos-vulnerability-firehose-hits-human-bottleneck"
  },
  {
    "id": "news-2e37e50c",
    "date": "2026-09-09",
    "dateLabel": "Sep 09, 2026",
    "category": "Security",
    "titleEN": "Identity-Based AI Attack Threatens Security of Enterprise Data",
    "titleIT": "Identity-Based AI Attack Threatens Security of Enterprise Data",
    "excerptEN": "\"Workflow identity hijacking\" can bypass standard security controls and hijack an organization's data by sending a basic request through an unauthenticated entry point.",
    "excerptIT": "[Sicurezza] \"Workflow identity hijacking\" can bypass standard security controls and hijack an organization's data by sending a basic request through an unauthenticated entry point.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/threat-intelligence/identity-based-ai-attack-security-enterprise-data"
  },
  {
    "id": "news-c439b4f7",
    "date": "2026-09-08",
    "dateLabel": "Sep 08, 2026",
    "category": "Security",
    "titleEN": "Stealing AI Reasoning Traces",
    "titleIT": "Stealing AI Reasoning Traces",
    "excerptEN": "Interesting research: “ Stealing Reasoning Traces from Proprietary LLM APIs “: Abstract: Leading large language model providers now conceal their models’ step-by-step reasoning, or chain-of-thought,...",
    "excerptIT": "[Sicurezza] Interesting research: “ Stealing Reasoning Traces from Proprietary LLM APIs “: Abstract: Leading large language model providers now conceal their models’ step-by-step reasoning,...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/09/stealing-ai-reasoning-traces.html"
  },
  {
    "id": "news-e8a63ed0",
    "date": "2026-09-04",
    "dateLabel": "Sep 04, 2026",
    "category": "ISACA",
    "titleEN": "Legally Defensible AI: Governance That Can Stand Up to Scrutiny",
    "titleIT": "Legally Defensible AI: Governance That Can Stand Up to Scrutiny",
    "excerptEN": "An organization can pass all compliance checkpoints yet still be indefensible once a regulator asks how its artificial intelligence system operates: the gap where legal defensibility sits.",
    "excerptIT": "[ISACA] An organization can pass all compliance checkpoints yet still be indefensible once a regulator asks how its artificial intelligence system operates: the gap where legal...",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/legally-defensible-ai-governance-that-can-stand-up-to-scrutiny"
  },
  {
    "id": "news-2eb95ecd",
    "date": "2026-09-04",
    "dateLabel": "Sep 04, 2026",
    "category": "Security",
    "titleEN": "Security Vulnerability in a Voting System",
    "titleIT": "Security Vulnerability in a Voting System",
    "excerptEN": "It’s a vulnerability that allows someone to recover the order of ballots cast, newly exploited with AI tools. Nearly four years since the original vulnerability was disclosed, I was still able to use...",
    "excerptIT": "[Sicurezza] It’s a vulnerability that allows someone to recover the order of ballots cast, newly exploited with AI tools. Nearly four years since the original vulnerability was disclosed, I...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/09/security-vulnerability-in-a-voting-system.html"
  },
  {
    "id": "news-b625ce18",
    "date": "2026-09-02",
    "dateLabel": "Sep 02, 2026",
    "category": "ISACA",
    "titleEN": "From Sample-Based Testing to Continuous Assurance: A Practical Take on AI-Driven Test Automation",
    "titleIT": "From Sample-Based Testing to Continuous Assurance: A Practical Take on AI-Driven Test Automation",
    "excerptEN": "AI-driven test automation, centered on large language models, retrieval-augmented generation, and human-in-the-loop governance, can enable continuous, comprehensive assurance.",
    "excerptIT": "[ISACA] AI-driven test automation, centered on large language models, retrieval-augmented generation, and human-in-the-loop governance, can enable continuous, comprehensive assurance.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/from-sample-based-testing-to-continuous-assurance-a-practical-take-on-ai-driven-test-automation"
  },
  {
    "id": "news-5443c496",
    "date": "2026-09-01",
    "dateLabel": "Sep 01, 2026",
    "category": "ISACA",
    "titleEN": "Risk Culture: The Part of Cybersecurity You Can’t Buy",
    "titleIT": "Risk Culture: The Part of Cybersecurity You Can’t Buy",
    "excerptEN": "When it comes to developing a healthy risk culture, actions speak louder than words and buying more tools does not address the core challenge.",
    "excerptIT": "[ISACA] When it comes to developing a healthy risk culture, actions speak louder than words and buying more tools does not address the core challenge.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/risk-culture-the-part-of-cybersecurity-you-cant-buy"
  },
  {
    "id": "news-03ac4207",
    "date": "2026-08-27",
    "dateLabel": "Aug 27, 2026",
    "category": "ISACA",
    "titleEN": "When Machines Understand Our Feelings: A Peek into Affective Computing",
    "titleIT": "When Machines Understand Our Feelings: A Peek into Affective Computing",
    "excerptEN": "Emotion AI has major implications in numerous industries and contexts, with significant privacy and ethical implications for digital trust practitioners to consider.",
    "excerptIT": "[ISACA] Emotion AI has major implications in numerous industries and contexts, with significant privacy and ethical implications for digital trust practitioners to consider.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/when-machines-understand-our-feelings-a-peek-into-affective-computing"
  }
];
