// ============================================================
//  news-data.js — GRC Prep Studio
//  Aggiornato automaticamente il 2026-07-15 09:13 UTC
//  Script: update_news.py | GitHub Actions
// ============================================================

const NEWS = [
  {
    "id": "news-5035c804",
    "date": "2026-07-15",
    "dateLabel": "Jul 15, 2026",
    "category": "Security",
    "titleEN": "Two SonicWall SMA 1000 Zero-Days Exploited, One Could Enable Admin Commands",
    "titleIT": "Two SonicWall SMA 1000 Zero-Days Exploited, One Could Enable Admin Commands",
    "excerptEN": "SonicWall has warned of active exploitation of two zero-day vulnerabilities impacting Secure Mobile Access (SMA) 1000 series appliances, one of which could be exploited to achieve arbitrary command...",
    "excerptIT": "[Sicurezza] SonicWall has warned of active exploitation of two zero-day vulnerabilities impacting Secure Mobile Access (SMA) 1000 series appliances, one of which could be exploited to achieve...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/two-sonicwall-sma-1000-zero-days.html"
  },
  {
    "id": "news-7d69aa96",
    "date": "2026-07-15",
    "dateLabel": "Jul 15, 2026",
    "category": "Security",
    "titleEN": "Nigeria Deepens Cybersecurity Efforts as Cybercriminals See More Profits",
    "titleIT": "Nigeria Deepens Cybersecurity Efforts as Cybercriminals See More Profits",
    "excerptEN": "The West African country advanced rules to force organizations to disclose cyberattacks, joining other nations in a shift to mandated transparency.",
    "excerptIT": "[Sicurezza] The West African country advanced rules to force organizations to disclose cyberattacks, joining other nations in a shift to mandated transparency.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyber-risk/nigeria-cybersecurity-efforts-cybercriminals-profits"
  },
  {
    "id": "news-b3309ba7",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Microsoft Patches Record 622 Flaws, Including Two Zero-Days Under Active Attack",
    "titleIT": "Microsoft Patches Record 622 Flaws, Including Two Zero-Days Under Active Attack",
    "excerptEN": "Microsoft shipped its largest Patch Tuesday on record today, and two of the fixes close holes that attackers are already exploiting. The release covers 622 of Microsoft's own CVEs by its Security...",
    "excerptIT": "[Sicurezza] Microsoft shipped its largest Patch Tuesday on record today, and two of the fixes close holes that attackers are already exploiting. The release covers 622 of Microsoft's own CVEs...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/microsoft-patches-record-622-flaws.html"
  },
  {
    "id": "news-15efec47",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "SAP Patches CVSS 9.9 NetWeaver ABAP Flaw That Could Expose or Modify Data",
    "titleIT": "SAP Patches CVSS 9.9 NetWeaver ABAP Flaw That Could Expose or Modify Data",
    "excerptEN": "SAP has rolled out updates to address multiple vulnerabilities as part of its July 2026 security updates, including a critical flaw in SAP NetWeaver Application Server ABAP. The vulnerability in...",
    "excerptIT": "[Sicurezza] SAP has rolled out updates to address multiple vulnerabilities as part of its July 2026 security updates, including a critical flaw in SAP NetWeaver Application Server ABAP. The...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/sap-patches-cvss-99-netweaver-abap-flaw.html"
  },
  {
    "id": "news-6d187435",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "LabubaRAT Masquerades as NVIDIA Software to Control Windows Hosts",
    "titleIT": "LabubaRAT Masquerades as NVIDIA Software to Control Windows Hosts",
    "excerptEN": "Cybersecurity researchers have flagged a previously undocumented Rust-based remote access trojan (RAT) codenamed LabubaRAT that masquerades as NVIDIA software to blend into target environments....",
    "excerptIT": "[Sicurezza] Cybersecurity researchers have flagged a previously undocumented Rust-based remote access trojan (RAT) codenamed LabubaRAT that masquerades as NVIDIA software to blend into target...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/labubarat-masquerades-as-nvidia.html"
  },
  {
    "id": "news-70931690",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "RabbitMQ Flaws Could Leak OAuth Secrets and Expose Cross-Tenant Queue Metadata",
    "titleIT": "RabbitMQ Flaws Could Leak OAuth Secrets and Expose Cross-Tenant Queue Metadata",
    "excerptEN": "Cybersecurity researchers have disclosed details of two access control-related flaws impacting the RabbitMQ message broker service that could allow attackers to leak OAuth client secrets, expose...",
    "excerptIT": "[Sicurezza] Cybersecurity researchers have disclosed details of two access control-related flaws impacting the RabbitMQ message broker service that could allow attackers to leak OAuth client...",
    "icon": "🔐",
    "link": "https://thehackernews.com/2026/07/rabbitmq-flaws-could-leak-oauth-secrets.html"
  },
  {
    "id": "news-16f2160c",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Manage Vendor Risk in a Few Practical Steps",
    "titleIT": "Manage Vendor Risk in a Few Practical Steps",
    "excerptEN": "Risk tolerance, exposure visibility, board oversight — handling third-party risk is complicated but achievable with disciplined, precise governance.",
    "excerptIT": "[Sicurezza] Risk tolerance, exposure visibility, board oversight — handling third-party risk is complicated but achievable with disciplined, precise governance.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyber-risk/manage-vendor-risk-in-a-few-practical-steps"
  },
  {
    "id": "news-04b5ee34",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Cursor IDE Auto-Executes Malicious Code in Poisoned Repos",
    "titleIT": "Cursor IDE Auto-Executes Malicious Code in Poisoned Repos",
    "excerptEN": "Researchers reported the vulnerability to Cursor in December, but it still remains in the popular AI coding platform and can be exploited in poisoned repository attacks.",
    "excerptIT": "[Sicurezza] Researchers reported the vulnerability to Cursor in December, but it still remains in the popular AI coding platform and can be exploited in poisoned repository attacks.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/application-security/cursor-ide-malicious-code-poisoned-repos"
  },
  {
    "id": "news-6f75dace",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Microsoft Patches a Record 570 Security Flaws",
    "titleIT": "Microsoft Patches a Record 570 Security Flaws",
    "excerptEN": "Microsoft Corp. today released software updates to plug at least 570 security holes in its Windows operating systems and other software, almost triple the number of vulnerabilities the software giant...",
    "excerptIT": "[Sicurezza] Microsoft Corp. today released software updates to plug at least 570 security holes in its Windows operating systems and other software, almost triple the number of...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/microsoft-patches-a-record-570-security-flaws/"
  },
  {
    "id": "news-8544f4a7",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Upcoming Speaking Engagements",
    "titleIT": "Upcoming Speaking Engagements",
    "excerptEN": "This is a current list of where and when I am scheduled to speak: I’m speaking (virtually) at the Policy-Relevant Privacy Research Workshop in Calgary, Canada, on Monday, July 20, 2026. I’m speaking...",
    "excerptIT": "[Sicurezza] This is a current list of where and when I am scheduled to speak: I’m speaking (virtually) at the Policy-Relevant Privacy Research Workshop in Calgary, Canada, on Monday, July 20,...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/upcoming-speaking-engagements-58.html"
  },
  {
    "id": "news-65389917",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Vulnerability in FIFA’s Network",
    "titleIT": "Vulnerability in FIFA’s Network",
    "excerptEN": "FIFA’s network was vulnerable to anyone with even minimal access.",
    "excerptIT": "[Sicurezza] FIFA’s network was vulnerable to anyone with even minimal access.",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/vulnerability-in-fifas-network.html"
  },
  {
    "id": "news-b20bcc4c",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "Minacce cyber abilitate dall’AI: i 4 fronti al centro della lettera della BCE alle banche",
    "titleIT": "Minacce cyber abilitate dall’AI: i 4 fronti al centro della lettera della BCE alle banche",
    "excerptEN": "La lettera del 7 luglio alle banche dell'Eurozona da parte della BCE chiede loro di presentare, entro il 31 ottobre 2026, un piano d'azione per rafforzare la cyber resilience contro le minacce...",
    "excerptIT": "[Sicurezza] La lettera del 7 luglio alle banche dell'Eurozona da parte della BCE chiede loro di presentare, entro il 31 ottobre 2026, un piano d'azione per rafforzare la cyber resilience...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/nuove-minacce/lettera-alle-banche-bce-4-fronti-per/"
  },
  {
    "id": "news-249d55a1",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Security",
    "titleEN": "L’AI inventa un nuovo ransomware nel browser: il rischio vero è che riduce la soglia tecnica",
    "titleIT": "L’AI inventa un nuovo ransomware nel browser: il rischio vero è che riduce la soglia tecnica",
    "excerptEN": "La tipica allucinazione generativa, a una prima occhiata, si è invece trasformata in un'AI in grado di generare ransomware nel browser, collegando il rischio ipotetico dei browser a una tecnica di...",
    "excerptIT": "[Sicurezza] La tipica allucinazione generativa, a una prima occhiata, si è invece trasformata in un'AI in grado di generare ransomware nel browser, collegando il rischio ipotetico dei browser...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/news/lai-inventa-un-nuovo-ransomware-nel-browser-il-rischio-vero-e-che-riduce-la-soglia-tecnica/"
  },
  {
    "id": "news-4574f438",
    "date": "2026-07-14",
    "dateLabel": "Jul 14, 2026",
    "category": "Tech",
    "titleEN": "Intelligenza artificiale, Chirichilli: “Crea valore solo se le persone restano protagoniste”",
    "titleIT": "Intelligenza artificiale, Chirichilli: “Crea valore solo se le persone restano protagoniste”",
    "excerptEN": "La direttrice People & Sustainability di Open Fiber, all'evento \"Crescere nella PA\", rilancia il ruolo della formazione continua, del reverse mentoring e del dialogo tra generazioni per accompagnare...",
    "excerptIT": "[Tecnologia] La direttrice People & Sustainability di Open Fiber, all'evento \"Crescere nella PA\", rilancia il ruolo della formazione continua, del reverse mentoring e del dialogo tra...",
    "icon": "📡",
    "link": "https://www.corrierecomunicazioni.it/digital-economy/intelligenza-artificiale-chirichilli-crea-valore-solo-se-le-persone-restano-protagoniste/"
  },
  {
    "id": "news-f818ab69",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "ISACA",
    "titleEN": "When Intelligence Becomes a Controlled Capability",
    "titleIT": "When Intelligence Becomes a Controlled Capability",
    "excerptEN": "As frontier AI systems grow in capability, governments are viewing them as strategic assets that impact cybersecurity, intelligence, economic competitiveness and national security.",
    "excerptIT": "[ISACA] As frontier AI systems grow in capability, governments are viewing them as strategic assets that impact cybersecurity, intelligence, economic competitiveness and national security.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/when-intelligence-becomes-a-controlled-capability"
  },
  {
    "id": "news-ae56a1df",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "Security",
    "titleEN": "'Yellow Teams' Are Defining the Future of AI Security",
    "titleIT": "'Yellow Teams' Are Defining the Future of AI Security",
    "excerptEN": "In some companies, engineers are building defense and attack tools to test the potential of artificial intelligence for cybersecurity — and its threat.",
    "excerptIT": "[Sicurezza] In some companies, engineers are building defense and attack tools to test the potential of artificial intelligence for cybersecurity — and its threat.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cybersecurity-operations/yellow-teams-defining-future-ai-security"
  },
  {
    "id": "news-226f5344",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "Security",
    "titleEN": "GigaWiper Lets Threat Actors Choose Their Own Destructive Attack",
    "titleIT": "GigaWiper Lets Threat Actors Choose Their Own Destructive Attack",
    "excerptEN": "A modular implant borrows from various malware families to combine both backdoor and wiper activities to maximize impact and minimize operational output.",
    "excerptIT": "[Sicurezza] A modular implant borrows from various malware families to combine both backdoor and wiper activities to maximize impact and minimize operational output.",
    "icon": "🔐",
    "link": "https://www.darkreading.com/cyberattacks-data-breaches/gigawiper-threat-actors-choose-their-own-destructive-attack"
  },
  {
    "id": "news-5a62312d",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "Security",
    "titleEN": "Lessons Learned from CISA’s Recent GitHub Leak",
    "titleIT": "Lessons Learned from CISA’s Recent GitHub Leak",
    "excerptEN": "The Cybersecurity and Infrastructure Security Agency (CISA) has issued a postmortem on a data leak in which a contractor published dozens of internal CISA credentials -- including AWS Govcloud keys...",
    "excerptIT": "[Sicurezza] The Cybersecurity and Infrastructure Security Agency (CISA) has issued a postmortem on a data leak in which a contractor published dozens of internal CISA credentials -- including...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/lessons-learned-from-cisas-recent-github-leak/"
  },
  {
    "id": "news-287a32e5",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "Security",
    "titleEN": "Spazio e cyber spazio non sono più separati: nasce il Polo Italiano che li unisce",
    "titleIT": "Spazio e cyber spazio non sono più separati: nasce il Polo Italiano che li unisce",
    "excerptEN": "Nasce il Polo Italiano per il Cyber e la Space Economy. Partnership strategica con gli Emirati Arabi per integrare cyber, intelligenza artificiale e sicurezza spaziale. Obiettivo: rafforzare...",
    "excerptIT": "[Sicurezza] Nasce il Polo Italiano per il Cyber e la Space Economy. Partnership strategica con gli Emirati Arabi per integrare cyber, intelligenza artificiale e sicurezza spaziale. Obiettivo:...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/news/spazio-e-cyber-spazio-non-sono-piu-separati-nasce-il-polo-italiano-che-li-unisce/"
  },
  {
    "id": "news-34747dd8",
    "date": "2026-07-13",
    "dateLabel": "Jul 13, 2026",
    "category": "Security",
    "titleEN": "VPN veloce: con NordVPN 75% di sconto e 3 mesi extra",
    "titleIT": "VPN veloce: con NordVPN 75% di sconto e 3 mesi extra",
    "excerptEN": "La nuova promozione NordVPN consente di ottenere una VPN veloce con uno sconto fino al 75% e 3 mesi extra inclusi sui piani biennali. L'offerta comprende anche strumenti avanzati per la sicurezza...",
    "excerptIT": "[Sicurezza] La nuova promozione NordVPN consente di ottenere una VPN veloce con uno sconto fino al 75% e 3 mesi extra inclusi sui piani biennali. L'offerta comprende anche strumenti avanzati...",
    "icon": "🔐",
    "link": "https://www.cybersecurity360.it/cultura-cyber/vpn-veloce-nordvpn/"
  },
  {
    "id": "news-86854ecd",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "ISACA",
    "titleEN": "The AI Intervention Layer: From AI Proof to Runtime Control",
    "titleIT": "The AI Intervention Layer: From AI Proof to Runtime Control",
    "excerptEN": "Effective artificial intelligence governance amid a complex threat landscape calls for decision-capable enforcement at runtime.",
    "excerptIT": "[ISACA] Effective artificial intelligence governance amid a complex threat landscape calls for decision-capable enforcement at runtime.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/the-ai-intervention-layer-from-ai-proof-to-runtime-control"
  },
  {
    "id": "news-7fbb51d5",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "Friday Squid Blogging: “Squidbleed” Vulnerability",
    "titleIT": "Friday Squid Blogging: “Squidbleed” Vulnerability",
    "excerptEN": "In a rare combined cybersecurity/squid post, a twenty-nine-year-old squid proxy bug can leak HTTP requests. As usual, you can also use this squid post to talk about the security stories in the news...",
    "excerptIT": "[Sicurezza] In a rare combined cybersecurity/squid post, a twenty-nine-year-old squid proxy bug can leak HTTP requests. As usual, you can also use this squid post to talk about the security...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/friday-squid-blogging-squidbleed-vulnerability.html"
  },
  {
    "id": "news-33e1784b",
    "date": "2026-07-10",
    "dateLabel": "Jul 10, 2026",
    "category": "Security",
    "titleEN": "AI Surveillance and Social Progress",
    "titleIT": "AI Surveillance and Social Progress",
    "excerptEN": "In the near future, AI -powered surveillance systems will be able to track everything we do in public, and much of what we do in private. And if we do something wrong—shoplift, litter, jaywalk, you...",
    "excerptIT": "[Sicurezza] In the near future, AI -powered surveillance systems will be able to track everything we do in public, and much of what we do in private. And if we do something wrong—shoplift,...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/ai-surveillance-and-social-progress.html"
  },
  {
    "id": "news-4f1c3e05",
    "date": "2026-07-09",
    "dateLabel": "Jul 09, 2026",
    "category": "Security",
    "titleEN": "The Language of AI Could Change How Humans Speak",
    "titleIT": "The Language of AI Could Change How Humans Speak",
    "excerptEN": "Because of the way they are trained, large language models capture only a slice of human language. They’re trained on the written word, from textbooks to social media posts, and our speech as...",
    "excerptIT": "[Sicurezza] Because of the way they are trained, large language models capture only a slice of human language. They’re trained on the written word, from textbooks to social media posts, and...",
    "icon": "🔐",
    "link": "https://www.schneier.com/blog/archives/2026/07/the-language-of-ai-could-change-how-humans-speak.html"
  },
  {
    "id": "news-26ceb73b",
    "date": "2026-07-08",
    "dateLabel": "Jul 08, 2026",
    "category": "Security",
    "titleEN": "Felons, Fraudsters Flog Offensive Cybersecurity Startup",
    "titleIT": "Felons, Fraudsters Flog Offensive Cybersecurity Startup",
    "excerptEN": "A cybersecurity startup dangling millions of dollars to acquire zero-day security vulnerabilities in popular software is run by a pair of far-right conspiracy theorists and convicted felons whose...",
    "excerptIT": "[Sicurezza] A cybersecurity startup dangling millions of dollars to acquire zero-day security vulnerabilities in popular software is run by a pair of far-right conspiracy theorists and...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/felons-fraudsters-flog-offensive-cybersecurity-startup/"
  },
  {
    "id": "news-28a99d87",
    "date": "2026-07-06",
    "dateLabel": "Jul 06, 2026",
    "category": "ISACA",
    "titleEN": "Making AI-Powered Audits Understandable: A Practical Guide Using COBIT EDM05",
    "titleIT": "Making AI-Powered Audits Understandable: A Practical Guide Using COBIT EDM05",
    "excerptEN": "While AI is rapidly transforming internal audits, promising faster insights and broader coverages than traditional audit approaches, many stakeholders don't fully understand how AI works or why they...",
    "excerptIT": "[ISACA] While AI is rapidly transforming internal audits, promising faster insights and broader coverages than traditional audit approaches, many stakeholders don't fully understand how...",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/making-ai-powered-audits-understandable-a-practical-guide-using-cobit-edm05"
  },
  {
    "id": "news-8395757d",
    "date": "2026-07-02",
    "dateLabel": "Jul 02, 2026",
    "category": "ISACA",
    "titleEN": "Vulnerability Is Not a Bug: It’s a State of Being",
    "titleIT": "Vulnerability Is Not a Bug: It’s a State of Being",
    "excerptEN": "The moment we treat vulnerability as a checklist item to close instead of a condition to continuously manage, we are asking for trouble.",
    "excerptIT": "[ISACA] The moment we treat vulnerability as a checklist item to close instead of a condition to continuously manage, we are asking for trouble.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/vulnerability-is-not-a-bug-its-a-state-of-being"
  },
  {
    "id": "news-f3f6d1e9",
    "date": "2026-07-02",
    "dateLabel": "Jul 02, 2026",
    "category": "Security",
    "titleEN": "FBI Seizes NetNut Proxy Platform, Popa Botnet",
    "titleIT": "FBI Seizes NetNut Proxy Platform, Popa Botnet",
    "excerptEN": "The Federal Bureau of Investigation (FBI) said today it worked with industry partners to seize hundreds of domains associated with NetNut, a sprawling residential proxy service operated by the...",
    "excerptIT": "[Sicurezza] The Federal Bureau of Investigation (FBI) said today it worked with industry partners to seize hundreds of domains associated with NetNut, a sprawling residential proxy service...",
    "icon": "🔐",
    "link": "https://krebsonsecurity.com/2026/07/fbi-seizes-netnut-proxy-platform-popa-botnet/"
  },
  {
    "id": "news-bbe8bc36",
    "date": "2026-07-01",
    "dateLabel": "Jul 01, 2026",
    "category": "ISACA",
    "titleEN": "The CISO vs. Shadow AI Cold War",
    "titleIT": "The CISO vs. Shadow AI Cold War",
    "excerptEN": "Organizations' biggest artificial intelligence risk may not be the model, but how shadow AI is being adopted across the enterprise.",
    "excerptIT": "[ISACA] Organizations' biggest artificial intelligence risk may not be the model, but how shadow AI is being adopted across the enterprise.",
    "icon": "🏛️",
    "link": "https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2026/the-ciso-vs-shadow-ai-cold-war"
  }
];
